image: docker.io/rust
stages:
  - check
  - test
  - publish

cargo-check:
  stage: check
  cache:
    paths:
      - target
  before_script:
    - rustup component add clippy
    - rustup component add rustfmt
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo fmt -- --check
    - cargo check
    - cargo clippy

cargo-test:
  stage: test
  cache:
    paths:
      - target
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --all --verbose

cargo-publish:
  stage: publish
  cache:
    paths:
      - target
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo publish --token ${CARGO_TOKEN}
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'

