[package]
name = "yggdrasil-keys"
version = "0.1.0"
authors = ["Jan Christian Grünhage <jan.christian@gruenhage.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = "2.1.0"
ed25519-dalek = "1.0.0-pre.3"
x25519-dalek = "0.6.0"
rand_core = "0.5.1"
sha2 = "0.9.0"
generic-array = "0.14.1"
hex = "0.4.2"
custom_error = "1.7.1"

[dev-dependencies]
rand = "0.7.3"
